### ISSUE TITLE
Timelime review article

### ISSUE THREAD

**Issue by egonw** [BiGCAT-UM/chem-rdf-model-review#4]
- [ ] Identify journal articles and sparql endpoints that describe and use RDF for chemical entities: #1 
- [ ] Identify used ontologies: #5 
- [ ] Write shape expressions (ShEx) to describe found models: #2 
- [ ] Write article: #3
